### ISSUE TITLE
Starting with 31.0.0 release golang needs Internet to build the project

### ISSUE THREAD

**Issue by vanaf** [nmeum/android-tools#47]
We ship go.sum file since 31.0.0 release, which comes with following boringssl commit: https://boringssl-review.googlesource.com/c/boringssl/+/42044
Without Internet build now fails with
```
[ 50%] Generating err_data.c
cd /builddir/build/BUILD/android-tools-31.0.2/vendor/boringssl/crypto/err && /usr/bin/go run err_data_generate.go > /builddir/build/BUILD/android-tools-31.0.2/x86_64-redhat-linux-gnu/vendor/boringssl/crypto/err_data.c
go: golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9: unrecognized import path "golang.org/x/crypto": https fetch: Get "https://golang.org/x/crypto?go-get=1": dial tcp: lookup golang.org: Temporary failure in name resolution
```

See full log: https://koji.fedoraproject.org/koji/taskinfo?taskID=73169944

**Comment by vanaf** [comment]
As a workaround we use
```
GO111MODULE=off
```
to let go search for modules in GOPATH.

**Comment by Biswa96** [comment]
Does this issue need to be fixed in this repository? Fedora spec file mentions the go modules explicitly, link https://src.fedoraproject.org/rpms/android-tools/blob/rawhide/f/android-tools.spec

**Comment by munix9** [comment]
This is also necessary in openSUSE on OBS, so the preliminary work of creating a `vendor.tar.gz` locally, since the OBS does not allow network access even during package building.

If possible, the appropriate vendor packages needed could be created in advance and then included in the finished package.

`gocryptfs` does it this way, see e.g. https://github.com/rfjakob/gocryptfs/releases - the package there is currently called `gocryptfs_v2.3_src-deps.tar.gz`.

For openSUSE I create the required `vendor.tar.gz` locally in advance and then refer in the spec file (after unpacking at the appropriate place) with export `GOFLAGS="-mod=vendor"` that no download is necessary.

**Comment by munix9** [comment]
I have now added the `go mod vendor` to the Google Action and it seems to work, see https://github.com/nmeum/android-tools/compare/master...munix9:android-tools:vendor

The corresponding package_source for testing is available in https://github.com/munix9/android-tools/actions/runs/4282460513

When compiling, at least an `export GOFLAGS="-mod=vendor"` must be done before.

**Comment by JamiKettunen** [comment]
I also hit this when packaging for [Chimera Linux](https://chimera-linux.org/), there I could workaround with:
```py
env = {"GOFLAGS": "-mod=vendor"}

def do_prepare(self):
    with self.pushd("vendor/boringssl"):
        self.do("go", "mod", "vendor", allow_network = True)
```
I'll try the proposed PR deps archive and report there in a bit

**Comment by Biswa96** [comment]
The 34.0.5 release source tarball now includes required go modules for boringssl. It was fixed in 1e417cc26f8c74daa5c96d5e11cdaa12a36063f0 commit. Thanks to munix9

**Comment by Biswa96** [comment]
New adb mdns features require rust language. Should rust crates also be added in source tarball for similar reasons?

**Comment by munix9** [comment]
There are probably several possible solutions here, but I’m referring more specifically to the situation with the Open Build Service (openSUSE).
As a general rule (for security reasons, among others), there is no network or Internet access during the build process.
For openSUSE’s OBS, this means that all sources required for the build process must be available in advance.
This includes the sources for the program itself, as well as all dependencies - either as pre-built distribution packages or, as with Go and Rust, as vendor archives.
To make the packaging of the android-tools as simple as possible while also keeping it flexible (which is probably the whole point of this project), I could envision one of the following alternatives:

1. a package as before, including all (vendor) dependencies
2. a package as before without (vendor) dependencies, plus an additional package containing only the (vendor) dependencies (vendor.tar.xz)
3. two packages: one as before without (vendor) dependencies and one including all (vendor) dependencies; as offered by [gocryptfs](https://github.com/rfjakob/gocryptfs/releases/tag/v2.6.1) ([Release-Tarballs](https://github.com/rfjakob/gocryptfs/wiki/Release-Tarballs)), for example
4. a package as before without (vendor) dependencies, but which must be prepared accordingly so that distributions can easily set up and provide the required (vendor) dependencies (for openSUSE, for example, this would be done via the OBS service [cargo_vendor](https://github.com/openSUSE-Rust/obs-service-cargo))

I prefer options 1, 2, or 3 and, for now, have no concerns about package size - if a feature is needed or offered, then the necessary dependencies must also be taken into account.

**Comment by Biswa96** [comment]
Thanks for the nice explanation. I prefer the option 2 because it will help to reduce the tarball size by removing huge test files.
