### ISSUE TITLE
Fastboot ends in "Segmentation Fault"

### ISSUE THREAD

**Issue by CastorDYvaine** [nmeum/android-tools#49]
I have aarch64 android-tools in termux, and am having an issue where fastboot gives an error message saying "Segmentation Fault".
I have uninstalled and then reinstalled android-tools.

Android 10 : Motorola Moto E7 : aarch64 : Unrooted Stock rom
![termux fboot err1](https://user-images.githubusercontent.com/88608105/139230937-3aa8f1da-a724-4dfa-93a5-6255f0f904dc.png)
![termux fboot err2](https://user-images.githubusercontent.com/88608105/139230947-055d29dd-a6b3-494d-820d-806b2ac27789.png)
![termux fboot err3](https://user-images.githubusercontent.com/88608105/139230950-6b08eb87-3bbb-409a-9f3c-5f832b5193f7.png)

**Comment by Johnnynator** [comment]
That bug is fixed in their packaging with termux/termux-packages/issues/7882 .

The backtrace I saw before checking their issue tracker was most likely fixed by this line change https://github.com/termux/termux-packages/pull/7882/files#diff-3f73b981194d1b1f8a51c2295ea09a5a75d569a61c15b94187852daf2143dc9cR22

**Comment by CastorDYvaine** [comment]
I fixed it somehow.
I ran it in gdb and it worked while in there, then I exited gdb and ran it normally and it worked (huh??).
Unfortunately I cannot provide logs as I am a noob at using gdb.
Thanks for your help anyways.
