### ISSUE TITLE
android-tools doesn't build for non-x86* arches

### ISSUE THREAD

**Issue by ollieparanoid** [nmeum/android-tools#6]
(I did not look into this much yet, this is more of an FYI that a downstream bugreport exists.)

The bundled boringssl fails to compile on Alpine for non-x86* arches. Maybe we can make it use the system's openssl instead?

Last build from Alpine:
http://build.alpinelinux.org/buildlogs/build-edge-armhf/testing/android-tools/android-tools-9.0.0_p3-r1.log

Downstream bugreport (user missing it for aarch64):
https://gitlab.com/postmarketOS/pmbootstrap/issues/1682

**Comment by nmeum** [comment]
I am aware of this problem. The problem is that I don't have access to non-x86* arches thus making it difficult for me to develop a fix. Additionally, I didn't research yet if non-x86* arches are actually supported by boringssl.

> Maybe we can make it use the system's openssl instead?

I would prefer not to since doing so probably requires a lot of patches thereby making it harder to upgrade to newer android-tools upstream versions in the future.

**Comment by ollieparanoid** [comment]
Fixed in https://github.com/alpinelinux/aports/commit/67283cdbf6ef0ce2912bd28297714d6bb3976a38
